# Generated by Django 6.0.1 on 2026-02-03 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='is_available',
        ),
    ]
