# Generated by Django 6.0.2 on 2026-03-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0002_remove_bike_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
