# Generated by Django 6.0.2 on 2026-03-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0003_bike_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='available_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='available_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
